package main

import (
	"text/template"
)

var tmpl, _ = template.New("inputgen").Parse("" + `
// Code generated by scripts/gqlgen2/gen.go. DO NOT EDIT.
package schema

import (
"encoding/json"

"github.com/graph-gophers/graphql-go"
)

{{- range $i, $source := . }}
type {{$source.Name}} struct {
{{- range $j, $prop := $source.Props }}
{{$prop.Name}} {{$prop.GoTypeName}} ` + "`" + `json:"{{$prop.SerializedName}}"` + "`" + `
{{- end}}
}

{{ end }}

{{- range $i, $source := . }}
func (i *{{$source.Name}}) Key() interface{} {
type key string
b, _ := json.Marshal(i)
return key(string(b))
}

func (i *{{$source.Name}}) MarshalJSON() ([]byte, error) {
return json.Marshal([]interface{}{
	{{- range $j, $prop := $source.Props }}{{if $j}}, {{end}}i.{{$prop.Name}}{{- end -}}
})
}
{{ end }}

var _ = graphql.ID("")

`)
