# Generated by Django 3.0.2 on 2020-01-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name_kr', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_value', models.FloatField()),
                ('high_value', models.FloatField()),
                ('low_value', models.FloatField()),
                ('close_value', models.FloatField()),
                ('adj_close_value', models.FloatField()),
                ('volume', models.IntegerField()),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predictor.Stock')),
            ],
        ),
    ]
