# Generated by Django 3.0.2 on 2020-01-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='date',
            new_name='record_date',
        ),
    ]
