# Generated by Django 3.0.2 on 2020-02-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20200123_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='adj_close_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
