# Generated by Django 3.0.2 on 2020-02-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20200206_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name_kr',
            new_name='name_ko',
        ),
        migrations.AlterModelTable(
            name='price',
            table='Price',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='Stock',
        ),
    ]
