# Generated by Django 3.0.2 on 2020-02-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_auto_20200213_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='SeriesDailyPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('high_value', models.FloatField()),
                ('low_value', models.FloatField()),
                ('close_value', models.FloatField()),
            ],
            options={
                'db_table': 'series_daily_prediction',
            },
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField()),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.AppUser')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.Stock')),
            ],
            options={
                'db_table': 'stock_prediction',
            },
        ),
        migrations.CreateModel(
            name='StockPredictionHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.StockPrediction')),
            ],
            options={
                'db_table': 'stock_prediction_holiday',
            },
        ),
        migrations.CreateModel(
            name='SeriesPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('C', 'Close'), ('H', 'High'), ('L', 'Low')], max_length=12)),
                ('created', models.DateTimeField()),
                ('mae', models.FloatField()),
                ('mape', models.FloatField()),
                ('stock_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.StockPrediction')),
            ],
            options={
                'db_table': 'series_prediction',
            },
        ),
    ]
