# Generated by Django 3.0.2 on 2020-02-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_appuser_seriesdailyprediction_seriesprediction_stockprediction_stockpredictionholiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeriesDailyPrediction',
        ),
    ]
