# Generated by Django 3.0.2 on 2020-02-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_delete_seriesdailyprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesDailyPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('series_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.SeriesPrediction')),
            ],
            options={
                'db_table': 'series_daily_prediction',
            },
        ),
    ]
