# Generated by Django 3.0.2 on 2020-02-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_seriesdailyprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesdailyprediction',
            name='series_prediction',
        ),
        migrations.RemoveField(
            model_name='seriesprediction',
            name='stock_prediction',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockpredictionholiday',
            name='request',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.DeleteModel(
            name='SeriesDailyPrediction',
        ),
        migrations.DeleteModel(
            name='SeriesPrediction',
        ),
        migrations.DeleteModel(
            name='StockPrediction',
        ),
        migrations.DeleteModel(
            name='StockPredictionHoliday',
        ),
    ]
