# Generated by Django 3.0.2 on 2020-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_auto_20200222_0747'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['stock_code', 'record_date'], name='price_stock_c_003d89_idx'),
        ),
    ]
